### ISSUE TITLE
add a configurable blacklist for banner names

### ISSUE THREAD

**Issue by RealMuffinTime** [MiraculixxT/bluemap-banner#2]
It would be nice, if you could a blacklist in the config.

As example, banners named 'Omnious Banner' wouldn't be created on the web map.

**Comment by MiraculixxT** [comment]
Implemented in the new version on [Modrinth](https://modrinth.com/plugin/bbanner)! There is now a list of strings inside the settings.yml file that are excluded from any banner placement (it will just do nothing, Omnious Banner is blocked by default. You might need to delete your settings once

**Comment by wallalex0** [comment]
Very nice, thank you.

**Comment by RealMuffinTime** [comment]
Perfect 2.
